### PR TITLE
Write lesson on setting up local coding environment

### PR DESCRIPTION
**Pull request by mdpiper**
This PR introduces a new CoCo lesson (number 0) on setting up a scientific coding environment--a Python distro, a terminal app, and a text editor--on a local computer. The lesson includes download links for recommended software and a brief explanation on why the software is used. The lesson is minimal: it will likely require some additional discussion in class.

@aguspesce @isamarcortes Please let me know if you're happy with the content of this lesson, and feel free to add comments and suggestions. Once you're OK with it, I'd appreciate your help in making a Spanish translation.

### CODE REVIEW

**Review by aguspesce — APPROVED** [review]
@mdpiper... I like it! This is the material for the first day when we will check installation, present them Jupyter and JupyterHub in case that someone couldn't install conda.
 
Let me know if it is ready, so I can work in the translation.

**Comment by mdpiper** [comment]
Thanks, @aguspesce! Yes, we can use this material the first week, right after introductions. I looked it over again, and I think it's ready for a translation. Thank you for your help!

**Comment by aguspesce** [comment]
@isamarcortes puedes revisar las traducciones por si se me paso algo

**Comment by aguspesce** [comment]
@mdpiper Let me know if you like the changes and then I will merge  it to main

**Pull request merged**
