### PR TITLE
Small edits to Markdown cells in Session 2 notebook

### PR DESCRIPTION
**Pull request by santisoler**
Small edits to the Session 2 notebook, mostly fixing typos or improving writing.
Normalize separation between the text in both languages through a horizontal line.
Usa el _tuteo_ en las versiones en español.

### CODE REVIEW

**Comment by santisoler** [comment]
I have some small comments that I would like to talk about.

1. In section 1.1 we state that we don't need to declare variables nor their types because Python is object-oriented. The reason why we don't need to declare variable types is because Python has dynamic type checking (lenguaje de tipado dinámico). For example, C++ is a object-oriented language but we need to declare variable types.
2. When we define data structures we state that they hold data with the same type. But this is not the case for lists, tuples (which can store variables of different type) or even dictionaries.
3. In the third formative assessment we offer the option to answer that `nothing happens`. I think this answer is poorly informative. If every student marks that one as the answer, it would be very hard for the instructors to figure out what kind of misunderstanding they have.

**Comment by aguspesce** [comment]
Thank @santisoler  for your corrections!

**Comment by aguspesce** [comment]
@santisoler can you fix it? the name of the notebook change now

**Review by aguspesce — APPROVED** [review]

**Comment by aguspesce** [comment]
@santisoler 

>  I have some small comments that I would like to talk about.
> 
> 1. In section 1.1 we state that we don't need to declare variables nor their types because Python is object-oriented. The reason why we don't need to declare variable types is because Python has dynamic type checking (lenguaje de tipado dinámico). For example, C++ is a object-oriented language but we need to declare variable types.
> 
> 2.  When we define data structures we state that they hold data with the same type. But this is not the case for lists, tuples (which can store variables of different type) or even dictionaries.
> 3. In the third formative assessment we offer the option to answer that nothing happens. I think this answer is poorly informative. If every student marks that one as the answer, it would be very hard for the instructors to figure out what kind of misunderstanding they have.

We can talk about this tomorow...

**Comment by santisoler** [comment]
> @santisoler can you fix it? the name of the notebook change now

Done!

**Comment by santisoler** [comment]
@aguspesce Can you merge this ASAP so we can use the modified notebook today?

**Review by aguspesce — APPROVED** [review]
Thank @santisoler!

**Pull request merged**
