### PR TITLE
Add homework and quizzes to lessons 1 and 2

### PR DESCRIPTION
**Pull request by mdpiper**
In this PR, I've added a homework section to lesson 1 (coding environment) and three formative assessment sections to lesson 2 (shell).

### CODE REVIEW

**Comment by mdpiper** [comment]
@aguspesce @isamarcortes Would you please help me with Spanish translations for these new sections? If it would be easier for you, you can add them as comments below & I can paste them into the lessons. Thank you!

**Comment by aguspesce** [comment]
I will do it today

**Review by aguspesce — APPROVED** [review]
I pushed the translations

**Comment by mdpiper** [comment]
Thank you, @aguspesce!

**Pull request merged**
